### PR TITLE
Update maintainer in README.md

### PR DESCRIPTION
**Pull request by qtuantruong**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [ ] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [ ] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by hmaarrfk** [comment]
how can we have any "proof" of this change?

**Comment by qtuantruong** [comment]
@hmaarrfk I'm the main contributor of Cornac as you can can see [here](https://github.com/PreferredAI/cornac/graphs/contributors). I've recently changed my username from [tqtg](https://github.com/tqtg) to [qtuantruong](https://github.com/qtuantruong). Let me know if anyhow I can show a better "proof".

**Comment by qtuantruong** [comment]
@hmaarrfk somehow I can't access to the tqtg account anymore. Whenever I try to login to using my email, it directs me to my new username (qtuantruong). I'm not even sure if GitHub created a new account using my old username by mistake or someone else have taken my old username. Please advise if any other way I can show a proof. Thanks

**Comment by qtuantruong** [comment]
One thing to note on the GitHub page of the [tqtg](https://github.com/tqtg) saying the account joined on July 15 2025 (the date I changed my username). It can't be that new account has been the maintainer of this feedstock which has been there since 2019.
Screenshot 2025-07-18 at 11 20 28 AM

**Comment by hmaarrfk** [comment]
Sorry for "being skeptical".

The "changing your username" seems like what you did.

It seems like someone decided to squat on your username.

Ok I looked an "old PR", and can see your name appearing there too
image

I'm going to use this as "justification".

Thanks for being patient and understanding my skepticism.

**Comment by qtuantruong** [comment]
got it. Seems that the tqtg username has been mapped to a different internal github ID I guess

**Comment by qtuantruong** [comment]
If we look at all previous PRs for this feedstock, my new username (qtuantruong) is the one who merged the PRs. I guess that also justifies qtuantruong was the true maintainer.

**Comment by qtuantruong** [comment]
@hmaarrfk Thanks for looking into and resolving my request. Really appreciate it!

**Comment by danielnachun** [comment]
@qtuantruong Looking quickly at your failure:
```
cornac/utils/external/eigen/Eigen/src/Core/Transpositions.h:387:87: error: no member named 'derived' in 'Transpose<TranspositionsBase<type-parameter-0-0>>'
  387 |       return Product<OtherDerived, Transpose, AliasFreeProduct>(matrix.derived(), trt.derived());
```
This is probably because `cornac` is vendoring a very old of `eigen`.  This is unfortunately a good example of why vendoring dependencies is a bad practice in general - if the vendored copy doesn't get updated frequently enough, it starts to have problems being built with newer compilers and non-vendored dependencies.  You may want to look into devendoring `eigen` and `boost` for this package - hopefully whatever they use those libraries for in `cornac` will work with a newer version of `eigen` and `boost`.

**Comment by qtuantruong** [comment]
@danielnachun thanks for looking into it. The `eigen` lib is also outdated (stopped developing since 2018). I guess we will need to take a closer look and make it compatible with the new build environment.

**Comment by danielnachun** [comment]
I guess the last stable release for `eigen` is from 2021 - you could try devendoring and depending on that version externally.  Alternatively if you want to use a linear algebra library this is more consistent about tagging releases, you might want to consider using [Armadillo](https://arma.sourceforge.net/download.html) instead.  I recently had great success porting Eigen code to Armadillo and found the API much simpler and easier to understand.
